# name of your application
export APPLICATION = hello-world

# If no BOARD is found in the environment, use this default:
export BOARD ?= native

# This has to be the absolute path to the RIOT base directory:
export RIOTBASE ?= $(CURDIR)/../..

#export RIOTCPU ?= $(CURDIR)/../../../thirdparty_cpu                        
#export RIOTBOARD ?= $(CURDIR)/../../../thirdparty_boards      

# Change this to 0 show compiler invocation lines by default:
export QUIET ?= 1

#export LINKFLAGS += -I../dyn_app/

include $(RIOTBASE)/Makefile.include
